# [START cloudbuild]
steps:
- name: 'python:3.7-slim'
  id: Run unit tests on the app
  entrypoint: /bin/sh
  args:
  - -c
  - |
      pip install flask
      python ./app/src/test_app.py

- name: 'alpine/helm:3.5.4'
  id: Run helm lint
  args:
  - 'lint'
  - 'charts/simple-helloworld-python-app'

- name: 'gcr.io/cloud-builders/docker'
  id: Build container image
  entrypoint: sh
  args:
  - -c
  - |
      cd app
      docker build -t 'gcr.io/$PROJECT_ID/simple-flask-helloworld-app:$SHORT_SHA' .

- name: 'gcr.io/cloud-builders/docker'
  id: Push container
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/simple-flask-helloworld-app:$SHORT_SHA'

# [END cloudbuild]