# [START cloudbuild]
steps:
- name: 'python:3.7-slim'
  id: Run unit tests on the app
  entrypoint: /bin/sh
  args:
  - -c
  - |
      pip install flask
      python ./app/src/test_app.py

- name: 'gcr.io/cloud-builders/docker'
  id: Build container image
  entrypoint: sh
  args:
  - -c
  - |
      cd app
      docker build -t 'gcr.io/$PROJECT_ID/hello-cloudbuild:$SHORT_SHA' .